### ISSUE TITLE
FoundryVTT v12 - Not mapping properly

### ISSUE THREAD

**Issue by Aeristoka** [esheyw/pf2e-community-monster-core-token-pack-mapping#5] opened 2024-06-30 15:01 UTC
This does not appear to be mapping properly in FoundryVTT v12 + pf2e 6.0.x. Are there plans to update it to support those versions?

**Comment by esheyw** [comment] 2024-06-30 18:02
There shouldn't have been any changes that prevent this from working exactly the same in v12. 'Not mapping properly' is not particularly descriptive, can you give a concrete example that breaks?

**Comment by Aeristoka** [comment] 2024-06-30 19:53
Further: It appears that anything "working" is just the default Token Bestiaries Pack, as disabling this Module doesn't change them.

The following don't work properly

- Aesra, sharing art with
  - Lantern Archon (Gestalt) (Bestiary 1)
  - Legion Archon (Bestiary 1)
- Barghest, sharing art with
  - Barghest (Bestiary 1)
- Cave Worm, sharing art with
  - Purple Worm (Bestiary 1)
- Centaur Herbalist, sharing art with
  - Centaur (Bestiary 1)
- Horned Dragon (Adult), sharing art with
  - Green Dragon (Adult) (Bestiary 1)
  - Green Dragon (Adult, Spellcaster) (Bestiary 1)
- Horned Dragon (Adult, Spellcaster), sharing art with
  - Green Dragon (Adult) (Bestiary 1)
  - Green Dragon (Adult, Spellcaster) (Bestiary 1)
- Horned Dragon (Ancient), sharing art with
  - Green Dragon (Ancient) (Bestiary 1)
  - Green Dragon (Ancient, Spellcaster) (Bestiary 1)
- Horned Dragon (Ancient, Spellcaster), sharing art with
  - Green Dragon (Ancient) (Bestiary 1)
  - Green Dragon (Ancient, Spellcaster) (Bestiary 1)
- Horned Dragon (Young), sharing art with
  - Green Dragon (Young) (Bestiary 1)
  - Green Dragon (Young, Spellcaster) (Bestiary 1)
- Horned Dragon (Young, Spellcaster), sharing art with
  - Green Dragon (Young) (Bestiary 1)
  - Green Dragon (Young, Spellcaster) (Bestiary 1)
- Qarna, sharing art with
  - Horned Archon (Bestiary 1)
- Sea Hag, sharing art with
  - Sea Hag (Bestiary 1)
- Tomb Jelly, sharing art with
  - Ochre Jelly (Bestiary 1)

**Comment by esheyw** [comment] 2024-07-01 06:26
Okay, well, I can confirm that this isn't just you, and it also seems to not be a new thing on v12, as I'm getting the exact same failures on my 11.315/pf2e 5.16.1 test world. Not sure when this broke, I haven't actually checked its integrity in a while. I have no idea *why* it did yet, I'm looking into it

**Comment by esheyw** [comment] 2024-07-01 07:19
This should be fixed in 1.2.0

**Closed as completed by esheyw** 2024-07-01 07:19 UTC

**Comment by Aeristoka** [comment] 2024-07-01 12:20
Can confirm, working properly now! Always happy to accidentally stumble into things that don't work.

You could also bump the verified compat to v12 in a 1.2.1 release or so, it does work fine on that version as well.

Any objection to me looking further into mappings that might make sense and submitting a PR? (no promises, just a thought I'm having this morning).

**Comment by esheyw** [comment] 2024-07-01 16:17
As the readme notes, I'm well open to suggested mappings. Honestly I haven't had an active game in so long I didn't even have this mod enabled in my test world, so I'm not likely to come up with any myself. Also, re: compatibility, yea, I knew I was forgetting something...

**Comment by Aeristoka** [comment] 2024-07-01 17:49
> As the readme notes, I'm well open to suggested mappings. Honestly I haven't had an active game in so long I didn't even have this mod enabled in my test world, so I'm not likely to come up with any myself. Also, re: compatibility, yea, I knew I was forgetting something...

A further question, do you have any opinions on mapping Similar-type creatures in things like:
Beginner Box
Pathfinder Society

To existing images? Or are you more inclined towards just new/big things like Monster Core?

**Comment by esheyw** [comment] 2024-07-01 17:55
Beginner Box I don't want to step on toes since the premium module does its own art mapping and we don't have a priority system (yet). Pathfinder Society, I don't touch it myself and don't own any of the premium modules, but the same concern exists. If I could reliably say `use the premium mappings over mine` I'd be fine with it; Core might be implementing art mapping above the system level and iirc priority is planned there, so fingers crossed for v13 I guess. 

On the other hand people can just turn the module off -- Truthfully idk.

**Comment by Aeristoka** [comment] 2024-07-01 19:27
All makes solid sense to me, thanks!
